version: '3'

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    container_name: zookeeper
    networks:
      - kafka-net

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "machine_learning:1:1"
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    depends_on:
      - zookeeper
    container_name: kafka
    networks:
      - kafka-net

  spark:
    build: ./spark
    depends_on:
      - kafka
    volumes:
      - ./spark:/app
    container_name: spark
    networks:
      - kafka-net

  producer:
    build: ./producer
    depends_on:
      - kafka
    volumes:
      - ./producer:/app
    container_name: producer
    networks:
      - kafka-net 